apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kiln
  labels:
    app.kubernetes.io/name: kiln
spec:
  to:
    kind: Service
    name: kiln
  port:
    targetPort: 8080
  tls:
    termination: edge