replicaCount: 1

image:
  repository: ghcr.io/kiiskila/klamm-kiln
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
